[package]
name = "ring_overflow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "readme.md"
description = "Full-ring overflow policies"
publish = true

[dependencies]
ring_stats = { workspace = true }
ring_types = { workspace = true }

[lints]
workspace = true
