[package]
name = "ring_trace"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "readme.md"
description = "Optional sequence-operation trace log"
publish = false

[dependencies]
ring_types = { workspace = true }

[lints]
workspace = true
