//! The root readme's measured-results table: what a row reads, the markdown a criterion run
//! renders it into, and the criterion tree those numbers are parsed from. The whole of
//! `examples/readme_results.rs` except its row table and argument parsing; kept here so the tests
//! can render, parse and splice without a benchmark run behind them.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

use super::output;

/// One benchmark id a row reads: `<group>/<function>/<value>`, the id `report` prints. A `value`
/// of `None` reads every value the group has — a producer sweep.
#[derive(Debug)]
pub struct Id {
  /// The criterion group.
  pub group: &'static str,
  /// The function id, the candidate and its mode included: `spsc/push1_popN`.
  pub function: &'static str,
  /// The parameter the id carries, or `None` for every parameter the run swept.
  pub value: Option<&'static str>,
}

impl Id {
  /// Whether `key`, the stored form of a result's id, is one this id reads.
  fn matches(&self, key: &str) -> bool {
    match self.value {
      Some(value) => key == format!("{}/{}/{}", self.group, self.function, value),
      None => {
        let base = format!("{}/{}", self.group, self.function);
        key == base || key.starts_with(&format!("{base}/"))
      }
    }
  }
}

/// One row of the readme table: the claim as the readme words it, and the two sides the cells
/// compute from.
#[derive(Debug)]
pub struct Row {
  /// The claim cell, verbatim.
  pub claim: &'static str,
  /// The in-house candidate's ids.
  pub inhouse: &'static [Id],
  /// The nearest alternative's ids; its first id's candidate names the cell.
  pub alternative: &'static [Id],
  /// Whether the row's Δ carries the readme's †: the footnote below the table says no noise floor
  /// was established for it, so even a confirmed-looking gap is not a confirmed lead. True for
  /// exactly the rows that footnote covers.
  pub unfloored: bool,
}

/// One benchmark's parsed result.
#[derive(Debug)]
pub struct Measurement {
  /// Records one iteration moves.
  pub elements: u64,
  /// The median iteration, in nanoseconds.
  pub median_ns: f64,
}

impl Measurement {
  /// The records per second the result stands for.
  fn rate(&self) -> f64 {
    self.elements as f64 * 1e9 / self.median_ns
  }
}

/// The table's inputs: benchmark id, as `report` prints it, to the result.
pub type Data = BTreeMap<String, Measurement>;

/// One side of a row: the records per second its ids stand for, low and high — equal when the side
/// reads one id.
type Span = (f64, f64);

/// The table and its provenance line, with the rows whose ids `data` lacks reported in `skipped`
/// rather than estimated. A side of one id renders one number; a side of several renders a min–max
/// range across them, one unit for both ends. The Δ compares each side's best, positive when the
/// in-house candidate is faster, bold from 5 % — under that is run-to-run noise; a row whose noise
/// floor was never established marks its Δ with the † its footnote refers to.
pub fn render(rows: &[Row], data: &Data, machine: &str) -> (String, Vec<String>) {
  let mut skipped = Vec::new();
  let mut table = String::new();
  for row in rows {
    let (Some(inhouse), Some(alternative)) = (span(row.inhouse, data), span(row.alternative, data)) else {
      skipped.push(format!("row skipped: no criterion data for {}", row.claim));
      continue;
    };
    let candidate = row.alternative[0]
      .function
      .split('/')
      .next()
      .unwrap_or(row.alternative[0].function);
    let _ = writeln!(
      table,
      "| {} | **{}** | {candidate} {} | {} |",
      row.claim,
      inhouse_cell(inhouse),
      alternative_cell(alternative, inhouse),
      delta(inhouse, alternative, row.unfloored)
    );
  }
  let mut fragment = format!("*Regenerated by ./verb/bench suite::readme — {machine}*\n\n");
  let _ = write!(
    fragment,
    "| Claim | in-house | nearest alternative | Δ |\n|---|---|---:|---:|\n{table}"
  );
  (fragment, skipped)
}

/// The records per second `ids` stand for, low and high: one number, or the range across the
/// values of a sweep. `None` when none of the ids has data.
fn span(ids: &[Id], data: &Data) -> Option<Span> {
  let mut found: Vec<f64> = Vec::new();
  for id in ids {
    found.extend(
      data
        .iter()
        .filter(|(key, _)| id.matches(key))
        .map(|(_, measurement)| measurement.rate()),
    );
  }
  let low = found.iter().copied().min_by(f64::total_cmp)?;
  let high = found.iter().copied().max_by(f64::total_cmp)?;
  Some((low, high))
}

/// The in-house cell, bold in the caller: a single id renders one number, a sweep a min–max range,
/// one unit for both of its ends — `334.1 M/s` or `125.3–290.1 M/s`.
fn inhouse_cell(side: Span) -> String {
  let (low, high) = side;
  if low == high {
    let (value, unit) = output::scaled(low);
    return format!("{value} {unit}");
  }
  let (low_value, low_unit) = output::scaled(low);
  let (high_value, high_unit) = output::scaled(high);
  if low_unit == high_unit {
    format!("{low_value}–{high_value} {high_unit}")
  } else {
    format!("{low_value} {low_unit}–{high_value} {high_unit}")
  }
}

/// The alternative's cell, in the readme's `rtrb 244` style: the unit is dropped when the in-house
/// cell beside it already carries the same one, and kept when the two sides differ.
fn alternative_cell(side: Span, inhouse: Span) -> String {
  let (low, high) = side;
  let (_, inhouse_unit) = output::scaled(inhouse.1);
  if low == high {
    let (value, unit) = output::scaled(low);
    return if unit == inhouse_unit {
      value
    } else {
      format!("{value} {unit}")
    };
  }
  let (low_value, low_unit) = output::scaled(low);
  let (high_value, high_unit) = output::scaled(high);
  if low_unit == high_unit && high_unit == inhouse_unit {
    format!("{low_value}–{high_value}")
  } else if low_unit == high_unit {
    format!("{low_value}–{high_value} {high_unit}")
  } else {
    format!("{low_value} {low_unit}–{high_value} {high_unit}")
  }
}

/// The Δ cell: the in-house best against the alternative's best, `{:+.0}%`, bold from 5 %. An
/// unfloored row marks its Δ with the readme's † whatever the size — its noise floor was never
/// established, so no gap of its is a confirmed lead.
fn delta(inhouse: Span, alternative: Span, unfloored: bool) -> String {
  let change = (inhouse.1 / alternative.1 - 1.0) * 100.0;
  let mut text = format!("{change:+.0}%");
  if unfloored {
    text.push('†');
  }
  if change.abs() >= 5.0 { format!("**{text}**") } else { text }
}

/// The markers the table lives between in the readme, each on its own line.
pub const START: &str = "<!-- measured-results:start -->";
pub const END: &str = "<!-- measured-results:end -->";

/// `readme` with the lines between the two markers replaced by `fragment`, the markers themselves
/// kept — splicing the same table again changes nothing. An error names the marker that went
/// missing, and the text is left alone.
pub fn splice(readme: &str, fragment: &str) -> Result<String, String> {
  let start = readme.find(START).ok_or_else(|| format!("no {START} marker"))?;
  let body = readme[start..].find('\n').ok_or_else(|| format!("{START} ends the file"))? + start + 1;
  let end = readme[body..].find(END).ok_or_else(|| format!("no {END} marker"))? + body;
  Ok(format!("{}{}{}", &readme[..body], fragment, &readme[end..]))
}

/// Every benchmark's median under criterion's directory, keyed the way `report` prints ids:
/// `<group>/<function>/<value>`. What a filtered run skipped simply is not there. A file whose
/// benchmark or estimates JSON does not parse — the shape a criterion output-format drift would
/// produce — is skipped, never estimated.
pub fn results(criterion: &Path) -> Data {
  let mut files = Vec::new();
  find(criterion, &mut files);
  let mut data = Data::new();
  for file in files {
    let Some(new_dir) = file.parent() else {
      continue;
    };
    let (Some(benchmark), Some(median)) = (json(&file), median(new_dir)) else {
      continue;
    };
    let text = |field: &str| benchmark[field].as_str().map(str::to_string);
    let (Some(group), Some(function)) = (text("group_id"), text("function_id")) else {
      continue;
    };
    let key = match text("value_str") {
      Some(value) => format!("{group}/{function}/{value}"),
      None => format!("{group}/{function}"),
    };
    data.insert(
      key,
      Measurement {
        elements: benchmark["throughput"]["Elements"].as_u64().unwrap_or(1),
        median_ns: median,
      },
    );
  }

  data
}

fn find(dir: &Path, files: &mut Vec<PathBuf>) {
  let Ok(read) = fs::read_dir(dir) else { return };
  for entry in read.flatten() {
    let path = entry.path();
    if path.is_dir() {
      find(&path, files);
    } else if path.ends_with("new/benchmark.json") {
      files.push(path);
    }
  }
}

fn json(path: &Path) -> Option<Value> {
  serde_json::from_str(&fs::read_to_string(path).ok()?).ok()
}

fn median(dir: &Path) -> Option<f64> {
  json(&dir.join("estimates.json"))?["median"]["point_estimate"].as_f64()
}
